idf_component_register(
    SRCS
        "main.c"
        "uart_parser.c"
        "web_server.c"
        "relay_logic.c"
        "status_led.c"
        "remote_server.c"
        "wifi_ap_provision.c"
        "factory_reset.c"
         "ntp_time.c"
    INCLUDE_DIRS
        "."
    EMBED_FILES
        "index.html"
        "logo.png"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_client
        esp_http_server
        esp-tls
        mbedtls
        json
        driver
        esp_timer
)
